---
# ------------------------------------------------------- #
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.
# ------------------------------------------------------- #
dc_name: "CAMPUS_A"
fabric_name: "HCA"

# --------------------------------------------- #
# Update p2p mtu 9000 -> 1500
# MTU 9000 not supported in vEOS-LAB
# --------------------------------------------- #
p2p_uplinks_mtu: 1500

# --------------------------------------------- #
# bgp update wait install command
# not supported in vEOS
# --------------------------------------------- #
bgp_update_wait_install: false

# --------------------------------------------- #
# Management interface default gateway
# --------------------------------------------- #
mgmt_gateway: "192.168.0.1"

# --------------------------------------------- #
# Adjust default bfd values to avoid high CPU
# --------------------------------------------- #
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

# --------------------------------------------- #
# Enable vlan aware bundles
# --------------------------------------------- #
evpn_vlan_aware_bundles: true

# --------------------------------------------- #
# Shutdown interfaces on devices that face
# undeployed peers
# --------------------------------------------- #
shutdown_interfaces_towards_undeployed_peers: true

# --------------------------------------------- #
# Shutdown interfaces that are not in use
# --------------------------------------------- #
interface_defaults:
  ethernet:
    shutdown: true

# --------------------------------------------- #
# bgp peer groups passwords
# --------------------------------------------- #
bgp_peer_groups: "{{ secrets.bgp_peer_groups }}"
  # ipv4_underlay_peers:
  #   password: "AQQvKeimxJu+uGQ/yYvv9w=="
  # evpn_overlay_peers:
  #   password: "q+VNViP5i4rVjW1cxFv2wA=="
  # mlag_ipv4_underlay_peer:
  #   password: "vnEaG8gMeQf3d3cN6PktXQ=="

# --------------------------------------------- #
# Spines
# --------------------------------------------- #
spine_bgp_defaults:
  - "distance bgp 20 200 200"
  - "graceful-restart restart-time 300"
  - "graceful-restart"

spine:
  defaults:
    platform: "vEOS-LAB"
    bgp_as: 65100
    loopback_ipv4_pool: "192.168.244.0/24"
  nodes:
    - name: "campus-a-spine1"
      id: 11
      mgmt_ip: "192.168.0.31/24"
    - name: "campus-a-spine2"
      id: 12
      mgmt_ip: "192.168.0.32/24"

# --------------------------------------------- #
# L3Leafs
# --------------------------------------------- #
leaf_bgp_defaults:
  - "distance bgp 20 200 200"
  - "graceful-restart restart-time 300"
  - "graceful-restart"
# --------------------------------------------- #
# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will
# automatically form MLAG pair
# --------------------------------------------- #
l3leaf:
  defaults:
    platform: "vEOS-LAB"
    loopback_ipv4_pool: "172.16.10.0/24"
    vtep_loopback_ipv4_pool: "172.16.11.0/24"
    uplink_interfaces:
      - "Ethernet1"
      - "Ethernet2"
    uplink_ipv4_pool: "172.16.0.0/24"
    mlag_peer_link_allowed_vlans: "2-4094"
    mlag_interfaces:
      - "Ethernet11"
      - "Ethernet12"
    mlag_peer_ipv4_pool: "10.255.255.0/24"
    mlag_peer_l3_ipv4_pool: "10.255.254.0/24"
    mlag_dual_primary_detection: true
    virtual_router_mac_address: "00:1c:73:00:dc:01"
    spanning_tree_mode: "mstp"
    spanning_tree_priority: 16384

  node_groups:
    - group: "campus-a-leaf1"
      bgp_as: 65101
      uplink_switches:
        - "campus-a-spine1"
        - "campus-a-spine2"

      nodes:
        - name: "campus-a-leaf1a"
          id: 13
          mgmt_ip: "192.168.0.33/24"
          uplink_switch_interfaces:
            - "Ethernet5"
            - "Ethernet5"

        - name: "campus-a-leaf1b"
          id: 14
          mgmt_ip: "192.168.0.34/24"
          uplink_switch_interfaces:
            - "Ethernet6"
            - "Ethernet6"

    - group: "campus-a-leaf2"
      bgp_as: 65102

      nodes:
        - name: "campus-a-leaf2a"
          id: 15
          mgmt_ip: "192.168.0.35/24"
          uplink_switch_interfaces:
            - "Ethernet7"
            - "Ethernet7"
          l3_interfaces:
            - name: "Ethernet3"
              ip_address: "169.254.10.0/31"
              enabled: true
          structured_config:
            router_bgp:
              bgp:
                default:
                  ipv4_unicast: false
              distance:
                external_routes: 20
                internal_routes: 200
                local_routes: 200
              graceful_restart:
                enabled: true
              maximum_paths:
                paths: 4
                ecmp: 4
              peer_groups:
                - name: "WAN"
                  remote_as: 65534
                  description: "WAN Routers"
                  bfd: true
                  send_community: "all"
                  maximum_routes: 12000
              neighbors:
                - ip_address: "169.254.10.1"
                  peer_group: "WAN"
                  description: "WAN Router"
              address_family_ipv4:
                peer_groups:
                  - name: "WAN"
                    activate: true

        - name: "campus-a-leaf2b"
          id: 16
          mgmt_ip: "192.168.0.36/24"
          uplink_switch_interfaces:
            - "Ethernet8"
            - "Ethernet8"
          l3_interfaces:
            - name: "Ethernet3"
              ip_address: "169.254.10.2/31"
              enabled: true
          structured_config:
            router_bgp:
              bgp:
                default:
                  ipv4_unicast: false
              distance:
                external_routes: 20
                internal_routes: 200
                local_routes: 200
              graceful_restart:
                enabled: true
              maximum_paths:
                paths: 4
                ecmp: 4
              peer_groups:
                - name: "WAN"
                  remote_as: 65534
                  description: "WAN Routers"
                  bfd: true
                  send_community: "all"
                  maximum_routes: 12000
              neighbors:
                - ip_address: "169.254.10.3"
                  peer_group: "WAN"
                  description: "WAN Router"
              address_family_ipv4:
                peer_groups:
                  - name: "WAN"
                    activate: true

# --------------------------------------------- #
# L2Leafs
# --------------------------------------------- #
l2leaf:
  defaults:
    mlag: false
    platform: "vEOS-LAB"
    uplink_switches:
      - "campus-a-leaf2a"
      - "campus-a-leaf2b"
    uplink_interfaces:
      - "Ethernet1"
      - "Ethernet2"

  node_groups:
    - group: "campus-a-leaf2"
      filter:

      nodes:
        - name: "campus-a-leaf2c"
          id: 17
          mgmt_ip: "192.168.0.41/24"
          uplink_switches:
            - "campus-a-leaf1a"
            - "campus-a-leaf1b"
          uplink_switch_interfaces:
            - "Ethernet5"
            - "Ethernet5"

        - name: "campus-a-leaf2d"
          id: 18
          mgmt_ip: "192.168.0.42/24"
          uplink_switches:
            - "campus-a-leaf1a"
            - "campus-a-leaf1b"
          uplink_switch_interfaces:
            - "Ethernet6"
            - "Ethernet6"
