---
# ----------------------------------- #
# HCA Tenants Networks
# ----------------------------------- #
tenants:
  # HCA Specific Information - VRFs / VLANs
  - name: "HCA"
    mac_vrf_vni_base: 10000
    vrfs:
      - name: "default"
        vrf_vni: 10
        svis:
          - id: 10
            name: "MGMT"
            enabled: true
            ip_address_virtual: "10.10.10.1/24"
          - id: 20
            name: "USER"
            enabled: true
            ip_address_virtual: "10.10.20.1/24"
          - id: 30
            name: "VOICE"
            enabled: true
            ip_address_virtual: "10.10.30.1/24"
          - id: 40
            name: "PACS"
            enabled: true
            ip_address_virtual: "10.10.40.1/24"

