---
# ------------------------------------------------------- #
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.
# ------------------------------------------------------- #
dc_name: "CAMPUS"
fabric_name: "HCA"
# --------------------------------------------- #
# Update p2p mtu 9000 -> 1500
# MTU 9000 not supported in vEOS-LAB
# --------------------------------------------- #
p2p_uplinks_mtu: 1500

# --------------------------------------------- #
# bgp update wait install command
# not supported in vEOS
# --------------------------------------------- #
bgp_update_wait_install: false

# --------------------------------------------- #
# Management interface default gateway
# --------------------------------------------- #
mgmt_gateway: "192.168.0.1"

# --------------------------------------------- #
# Adjust default bfd values to avoid high CPU
# --------------------------------------------- #
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

interface_defaults:
  ethernet:
    shutdown: true

# BGP defaults
bgp_default_ipv4_unicast: true

# ----------------------------------- #
# Spines
# ----------------------------------- #
l3spine:
  defaults:
    platform: "vEOS"
    mgmt_interface: "Management1"
    spanning_tree_mode: "mstp"
    loopback_ipv4_pool: "172.16.40.0/24"
    vtep_loopback_ipv4_pool: "172.16.41.0/24"
    mlag_peer_ipv4_pool: "192.168.255.0/24"
    mlag_peer_l3_ipv4_pool: "192.168.254.0/24"
    mlag_peer_link_allowed_vlans: "2-4094"
    virtual_router_mac_address: 00:1c:73:00:dc:01
    mlag_interfaces:
      - "Ethernet11"
      - "Ethernet12"
    bgp_defaults:
      - "distance bgp 20 200 200"
      - "graceful-restart restart-time 300"
      - "graceful-restart"

  node_groups:
    - group: "campus-d-spines"
      bgp_as: "65401"
      nodes:
        - name: "campus-d-spine1"
          id: 1
          mgmt_ip: "192.168.0.61"
          l3_interfaces:
            - name: "Ethernet1"
              ip_address: "169.254.40.0/31"
              enabled: true
          structured_config:
            router_bgp:
              bgp:
                default:
                  ipv4_unicast: false
              as: 65401
              distance:
                external_routes: 20
                internal_routes: 200
                local_routes: 200
              graceful_restart:
                enabled: true
              maximum_paths:
                paths: 4
                ecmp: 4
              peer_groups:
                - name: "WAN"
                  remote_as: 65534
                  description: "WAN Routers"
                  bfd: true
                  send_community: "all"
                  maximum_routes: 12000
              neighbors:
                - ip_address: "169.254.40.1"
                  peer_group: "WAN"
                  description: "WAN Router"

        - name: "campus-d-spine2"
          id: 2
          mgmt_ip: "192.168.0.62"
          l3_interfaces:
            - name: "Ethernet1"
              ip_address: "169.254.40.2/31"
              enabled: true
          structured_config:
            router_bgp:
              bgp:
                default:
                  ipv4_unicast: false
              as: 65401
              distance:
                external_routes: 20
                internal_routes: 200
                local_routes: 200
              graceful_restart:
                enabled: true
              maximum_paths:
                paths: 4
                ecmp: 4
              peer_groups:
                - name: "WAN"
                  remote_as: 65534
                  description: "WAN Routers"
                  bfd: true
                  send_community: "all"
                  maximum_routes: 12000
              neighbors:
                - ip_address: "169.254.40.3"
                  peer_group: "WAN"
                  description: "WAN Router"

# ----------------------------------- #
# Leafs
# ----------------------------------- #
l2leaf:
  defaults:
    uplink_switches:
      - "campus-d-spine1"
      - "campus-d-spine2"
    uplink_interfaces:
      - "Ethernet1"
      - "Ethernet2"
    mlag_interfaces:
      - "Ethernet11"
      - "Ethernet12"
    mlag_peer_ipv4_pool: "192.168.255.0/24"
    mlag_peer_link_allowed_vlans: "2-4094"
    spanning_tree_mode: "mstp"
    mlag: true
    always_configure_ip_routing: true

# ----------------------------------- #
# Leaf1
# ----------------------------------- #
  node_groups:
    - group: "campus-d-leaf1"
      platform: "vEOS"
      nodes:
        - name: "campus-d-leaf1a"
          id: 1
          mgmt_ip: "192.168.0.63"
          uplink_switch_interfaces:
            - "Ethernet5"
            - "Ethernet5"

        - name: "campus-d-leaf1b"
          id: 2
          mgmt_ip: "192.168.0.64"
          uplink_switch_interfaces:
            - "Ethernet6"
            - "Ethernet6"

    - group: "campus-d-leaf2"
      platform: "vEOS"
      nodes:
        - name: "campus-d-leaf2a"
          id: 3
          mgmt_ip: "192.168.0.65"
          uplink_switch_interfaces:
            - "Ethernet7"
            - "Ethernet7"
        - name: "campus-d-leaf2b"
          id: 4
          mgmt_ip: "192.168.0.66"
          uplink_switch_interfaces:
            - "Ethernet8"
            - "Ethernet8"

# ----------------------------------- #
# Leaf2
# ----------------------------------- #
    - group: "campus-d-leaf2c"
      platform: "vEOS"
      mlag: false
      nodes:
        - name: "campus-d-leaf2c"
          id: 5
          mgmt_ip: "192.168.0.67"
          uplink_switches:
            - "campus-d-leaf2a"
            - "campus-d-leaf2b"
          uplink_switch_interfaces:
            - "Ethernet5"
            - "Ethernet5"
    - group: "campus-d-leaf2d"
      platform: "vEOS"
      mlag: false
      nodes:
        - name: "campus-d-leaf2d"
          id: 6
          mgmt_ip: "192.168.0.68"
          uplink_switches:
            - "campus-d-leaf2a"
            - "campus-d-leaf2b"
          uplink_switch_interfaces:
            - "Ethernet6"
            - "Ethernet6"

