---
# ------------------------------------------------------- #
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.
# ------------------------------------------------------- #
dc_name: "CAMPUS"
fabric_name: "HCA"

# --------------------------------------------- #
# Update p2p mtu 9000 -> 1500
# MTU 9000 not supported in vEOS-LAB
# --------------------------------------------- #
p2p_uplinks_mtu: 1500

# --------------------------------------------- #
# bgp update wait install command
# not supported in vEOS
# --------------------------------------------- #
bgp_update_wait_install: false

# --------------------------------------------- #
# Management interface default gateway
# --------------------------------------------- #
mgmt_gateway: "172.16.0.1"

# --------------------------------------------- #
# Adjust default bfd values to avoid high CPU
# --------------------------------------------- #
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

# --------------------------------------------- #
# Enable vlan aware bundles
# --------------------------------------------- #
evpn_vlan_aware_bundles: true

# --------------------------------------------- #
# Shutdown interfaces on devices that face
# undeployed peers
# --------------------------------------------- #
shutdown_interfaces_towards_undeployed_peers: true

# --------------------------------------------- #
# Shutdown interfaces that are not in use
# --------------------------------------------- #
interface_defaults:
  ethernet:
    shutdown: true

# --------------------------------------------- #
# bgp peer groups passwords
# --------------------------------------------- #
bgp_peer_groups:
  ipv4_underlay_peers:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  evpn_overlay_peers:
    password: "q+VNViP5i4rVjW1cxFv2wA=="
  mlag_ipv4_underlay_peer:
    password: "vnEaG8gMeQf3d3cN6PktXQ=="

# --------------------------------------------- #
# MARK: Tags
# --------------------------------------------- #
# generate_cv_tags:
#   topology_hints: true

# --------------------------------------------- #
# MARK: Spines
# --------------------------------------------- #
spine_bgp_defaults:
  - "distance bgp 20 200 200"
  - "graceful-restart restart-time 300"
  - "graceful-restart"

spine:
  defaults:
    platform: "vEOS-LAB"
    bgp_as: "65101"
    loopback_ipv4_pool: "192.168.244.0/24"
    mlag_peer_ipv4_pool: "10.255.255.0/24"
    mlag_peer_l3_ipv4_pool: "10.255.254.0/24"
  nodes:
    - name: "CAMPUS-Spine1"
      id: 11
      mgmt_ip: "172.16.0.31/24"
    - name: "CAMPUS-Spine2"
      id: 12
      mgmt_ip: "172.16.0.32/24"

# --------------------------------------------- #
# MARK: L3Leafs
# --------------------------------------------- #
leaf_bgp_defaults:
  - "distance bgp 20 200 200"
  - "graceful-restart restart-time 300"
  - "graceful-restart"
# --------------------------------------------- #
# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will
# automatically form mlag pair
# --------------------------------------------- #
l3leaf:
  defaults: "{{ L3LEAF_DEFAULTS.defaults }}"
  #   platform: "vEOS-LAB"
  #   loopback_ipv4_pool: "192.168.244.0/24"
  #   vtep_loopback_ipv4_pool: "192.168.243.0/24"
  #   uplink_interfaces:
  #     - "Ethernet1"
  #     - "Ethernet2"
  #   uplink_switches:
  #     - "CAMPUS-Spine1"
  #     - "CAMPUS-Spine2"
  #   uplink_ipv4_pool: "172.31.254.0/23"
  #   mlag_peer_link_allowed_vlans: "2-4094"
  #   mlag_interfaces:
  #     - "Ethernet3"
  #     - "Ethernet4"
  #   mlag_peer_ipv4_pool: "10.255.255.0/24"
  #   mlag_peer_l3_ipv4_pool: "10.255.254.0/24"
  #   mlag_dual_primary_detection: true
  #   virtual_router_mac_address: "00:1c:73:00:dc:01"
  #   spanning_tree_mode: "mstp"
  #   spanning_tree_priority: 16384
  node_groups:
    - group: "CAMPUS_Leaf1"
      bgp_as: "65102"
      rack: "Rack1A"
      filter:
        tags:
          - "l3leaf"
          - "opzone"
      nodes:
        - name: "CAMPUS-Leaf1A"
          id: 13
          mgmt_ip: "172.16.0.33/24"
          uplink_switch_interfaces:
            - "Ethernet1"
            - "Ethernet1"
          l3_interfaces:
            - name: "Ethernet7"
              description: "FRR_Linux1_ens3"
              ip_address: "10.13.13.1/24"
        - name: "CAMPUS-Leaf1B"
          id: 14
          mgmt_ip: "172.16.0.34/24"
          uplink_switch_interfaces:
            - "Ethernet2"
            - "Ethernet2"
    - group: "CAMPUS_Leaf2"
      bgp_as: "65103"
      filter:
        tags:
          - "l3leaf"
          - "opzone"
          - "Internet"
      nodes:
        - name: "CAMPUS-Leaf2A"
          id: 15
          mgmt_ip: "172.16.0.35/24"
          uplink_switch_interfaces:
            - "Ethernet3"
            - "Ethernet3"
        - name: "CAMPUS-Leaf2B"
          id: 16
          mgmt_ip: "172.16.0.36/24"
          uplink_switch_interfaces:
            - "Ethernet4"
            - "Ethernet4"
    - group: "CAMPUS_Leaf3"
      bgp_as: "65104"
      filter:
        tags:
          - "l3leaf"
      nodes:
        - name: "CAMPUS-Leaf3A"
          id: 15
          mgmt_ip: "172.16.0.37/24"
          uplink_switch_interfaces:
            - "Ethernet5"
            - "Ethernet5"
        - name: "CAMPUS-Leaf3B"
          id: 16
          mgmt_ip: "172.16.0.38/24"
          uplink_switch_interfaces:
            - "Ethernet6"
            - "Ethernet6"
    - group: "CAMPUS_Leaf4"
      bgp_as: "65105"
      filter:
        tags:
          - "l3leaf"
      nodes:
        - name: "CAMPUS-Leaf4A"
          id: 15
          mgmt_ip: "172.16.0.39/24"
          uplink_switch_interfaces:
            - "Ethernet7"
            - "Ethernet7"
        - name: "CAMPUS-Leaf3B"
          id: 16
          mgmt_ip: "172.16.0.40/24"
          uplink_switch_interfaces:
            - "Ethernet8"
            - "Ethernet8"

# --------------------------------------------- #
# MARK: L2Leafs
# --------------------------------------------- #
l2leaf:
  defaults:
    platform: "vEOS-LAB"
    uplink_switches:
      - "CAMPUS-Leaf2A"
      - "CAMPUS-Leaf2B"
    uplink_interfaces:
      - "Ethernet1"
      - "Ethernet2"
  node_groups:
    - group: "CAMPUS-L2Leaf2"
      filter:
        tags:
          - "l2leaf"
      nodes:
        - name: "CAMPUS-Leaf2C"
          id: 19
          mgmt_ip: "172.16.0.41/24"
          uplink_switches:
            - "CAMPUS-Leaf2A"
            - "CAMPUS-Leaf2B"
          uplink_switch_interfaces:
            - "Ethernet5"
            - "Ethernet5"
        - name: "CAMPUS-Leaf2D"
          id: 19
          mgmt_ip: "172.16.0.42/24"
          uplink_switches:
            - "CAMPUS-Leaf2A"
            - "CAMPUS-Leaf2B"
          uplink_switch_interfaces:
            - "Ethernet6"
            - "Ethernet6"
    - group: "CAMPUS_L2Leaf5"
      filter:
        tags:
          - "l2leaf"
      nodes:
        - name: "CAMPUS-Leaf5C"
          id: 20
          mgmt_ip: "172.16.0.43/24"
          uplink_switches:
            - "CAMPUS-Leaf4A"
            - "CAMPUS-Leaf4B"
          uplink_switch_interfaces:
            - "Ethernet5"
            - "Ethernet5"
        - name: "CAMPUS-Leaf5N"
          id: 20
          mgmt_ip: "172.16.0.44/24"
          uplink_switches:
            - "CAMPUS-Leaf4A"
            - "CAMPUS-Leaf4B"
          uplink_switch_interfaces:
            - "Ethernet6"
            - "Ethernet6"
# --------------------------------------------- #
# L3 Edge port definitions. This can be any port
# in the entire Fabric, where IP interfaces are
# defined
# MARK: DCI
# --------------------------------------------- #

# l3_edge:
#   # ------------------------------------------- #
#   # Define a new IP pool that will be used to
#   # assign IP addresses to L3 Edge interfaces
#   # ------------------------------------------- #
#   p2p_links_ip_pools:
#     - name: "DCI_IP_pool"
#       ipv4_pool: 172.16.100.0/24
#   # ------------------------------------------- #
#   # Define a new link profile which will match
#   # the IP pool, the used ASNs and include the
#   # defined interface into underlay routing
#   # ------------------------------------------- #
#   p2p_links_profiles:
#     - name: "DCI_profile"
#       ip_pool: "DCI_IP_pool"
#       mtu: 9164
#       as:
#         - 65103
#         - 65203
#       include_in_underlay_protocol: true
#   # ------------------------------------------- #
#   # Define each P2P L3 link and link the nodes,
#   # the interfaces and the profile used
#   # ------------------------------------------- #
#   p2p_links:
#     - id: 1
#       nodes:
#         - "CAMPUS-Leaf5A"
#         - "RE-DC2-Leaf5A"
#       interfaces:
#         - "Ethernet7"
#         - "Ethernet7"
#       profile: "DCI_profile"
#     - id: 2
#       nodes:
#         - "CAMPUS-Leaf2B"
#         - "RE-DC2-Leaf2B"
#       interfaces:
#         - "Ethernet7"
#         - "Ethernet7"
#       profile: "DCI_profile"
