---
# RE-DC1 Tenants Networks
# Documentation of Tenant specific information - Vlans/VRFs
tenants:
  # Tenant A Specific Information - VRFs / VLANs
  - name: "HCA"
    mac_vrf_vni_base: 10000
    vrfs:
      # - name: "Internet"
      #   vrf_vni: 999
      #   vtep_diagnostic:
      #     loopback: 999
      #     loopback_ip_range: 192.168.201.0/24
      #   static_routes:
      #     - destination_address_prefix: "0.0.0.0/0"
      #       gateway: "192.168.20.1"
      #       name: "To_Internet"
      #       nodes:
      #         - "RE-DC1-Leaf2A"
      #         - "RE-DC1-Leaf2B"
      #   svis:
      #     - id: 999
      #       name: "To_Internet"
      #       tags:
      #         - "Internet"
      #       enabled: true
      #       nodes:
      #         - node: "RE-DC1-Leaf2A"
      #           ip_virtual_router_addresses:
      #             - "192.168.20.98"
      #         - node: "RE-DC1-Leaf2B"
      #           ip_virtual_router_addresses:
      #             - "192.168.20.99"

      - name: "Blue"
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: "192.168.200.0/24"
        svis:
          - id: 110
            name: "Blue_110"
            tags:
              - "blue"
            enabled: true
            ip_address_virtual: "192.168.210.1/24"
          - id: 111
            vni_override: 50111
            name: "Blue_111"
            tags:
              - "blue"
            enabled: true
            ip_address_virtual: "192.168.211.1/24"
          - id: 112
            vni_override: 50112
            name: "Blue_112"
            tags:
              - "blue"
            enabled: true
            ip_address_virtual: "192.168.212.1/24"
          - id: 113
            name: "Blue_113"
            tags:
              - "blue"
            enabled: true
            ip_address_virtual: "192.168.213.1/24"

      - name: "Red"
        vrf_vni: 11
        svis:
          - id: 120
            name: "Red_120"
            tags:
              - "red"
            enabled: true
            ip_address_virtual: "192.168.220.1/24"
          - id: 121
            name: "WEBZone_121"
            tags:
              - "red"
            enabled: true
            ip_address_virtual: "192.168.221.1/24"
      - name: "Green"
        vrf_vni: 12
        svis:
          - id: 130
            name: "Green_130"
            tags:
              - "green"
            enabled: true
            ip_address_virtual: "192.168.230.1/24"
          - id: 131
            name: "Green_131"
            tags:
              - "green"
            enabled: true
            ip_address_virtual: "192.168.231.1/24"
