$ANSIBLE_VAULT;1.1;AES256
36326664633338333036383530646437633461623061306462633734396339613061666436646635
3633343665653031323864663363313330633363353931610a623433346233303865393932626461
32626531616635323263306231363962323430353965333935396637376165643962303239363337
3664333734313234390a353763306330333664383035653330343634636362343738343661626133
30366537396537393663646666373530393936363739303263653834623762313334356135646134
32313536393062356637623938656562393539646335313933323866303339663234356166383562
38643363316132653833313064393233353438663435326539353366643335323237326565316432
63343261363832663663323365376261396331633031613231333235663536363562353138316533
3764
